### ISSUE TITLE
well i want to add something like a post install script of some type

### ISSUE THREAD

**Issue by dr-nemesis-96** [kotoko/voidlinux-iso-extra#2]
i am sorry i am posting it like this
but i really want to make a live iso for my and others convinience

![download (1)](https://user-images.githubusercontent.com/103036804/209801961-3f3224f9-505c-4c18-8743-ba6cb6bdf63e.png)

most linux users want a distro that is fast and looks good, i think nordic theme generally looks good so is there any way i can write a script that is executed to copy the config files to proper place???
and yes sorry this may be a very dumb question
also i want to bundle some extra packages too, that arent in the official repos, i have build them with xbps-src, any way i can bundle them(um they do not have restricted lisencing, like for example ungoogled-chromium,Ananicy, just for convinience)?

thanx in advance

**Comment by kotoko** [comment]
If you search for help from people I suggest asking on reddit:
https://old.reddit.com/r/voidlinux/

All the job of generating ISO does script `mklive.sh`:
https://github.com/void-linux/void-mklive/blob/master/mklive.sh.in
There is flag `-I <includedir>` with description `Include directory structure under given path into rootfs`. Maybe that does the work?
If you are fluid with writing bash scripts i think you could 1. fork repository with script mklive.sh 2. modify file `mklive.sh.in` 3. use forked repository in `gen.sh`. `mklive.sh.in` looks very readable (and is not changed that often), so you could add post install scripts somewhere in there.

Last time I searched i did not find ready-to-use method for post install scripts. I agree it would useful.

I use issues for this repository for tracking bugs/regressions so I will close this issue.
